### ISSUE TITLE
デモページでダイアログが開きません

### ISSUE THREAD

**Issue by makinux** [gsi-cyberjapan/gsimaps-globe#1]
http://gsi-cyberjapan.github.io/gsimaps-globe/index_globe.html
のdemoページにおいて情報やファイルから読み込みなどのダイアログが開きません。
以下のファイルがNot Foundになっていたので、github pagesにデブロイされていないのではないでしょうか。

http://gsi-cyberjapan.github.io/gsimaps-globe/ThirdParty/dojo-release-1.9.3/dijit/_base/manager.js

**Comment by johofukyu** [comment]
ご指摘ありがとうございます。

「manager.js」が置いてあるディレクトリ（_base）の名前がアンダースコアで始まっていたため、
GitHubの仕様により、そのディレクトリの配下のファイルが読み込まれない状態になっておりました。

下記のページを参考に、「.nojekyll」を置いたことで、現在はデモページでもダイアログが開くようになっております。

Bypassing Jekyll on GitHub Pages
https://github.com/blog/572-bypassing-jekyll-on-github-pages

以上、よろしくお願いいたします。

**Comment by makinux** [comment]
修正を確認できました！
素早い対応有難うございます！
